inherit_gem:
  rubocop-shopify: rubocop.yml

AllCops:
  Include:
    - Rakefile
    - Gemfile
    - 'lib/**/*.rb'
  Exclude:
    - ruby-eupago.gemspec
    - vendor/**/*
    - Rakefile.rb

Metrics/MethodLength:
  Enabled: false

Style/ClassMethodsDefinitions:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false